### ISSUE TITLE
Install module 'discoverlib'

### ISSUE THREAD

**Issue by YongmingFrankGe** [favyen/otif#1]
I got 
```
Traceback (most recent call last):
  File "tracker.py", line 1, in <module>
    from discoverlib import geom
ModuleNotFoundError: No module named 'discoverlib'
```
when I try to run 
```
go run iou-tracker2.go /path/to/otif-dataset/ shibuya /path/to/otif-dataset/dataset/shibuya/valid/video/ /path/to/otif-dataset/dataset/shibuya/valid/yolov3-1280x704/ ./1280x704_tracks/ iou '' '{"Thresholds":[0,1,1,1,1,1,1]}'
```
Which module is this? How can we install it?

**Comment by YongmingFrankGe** [comment]
Realize it should be: https://github.com/mitroadmaps/roadtracer-beta/blob/master/discoverlib/geom.py
It'd be good to have a confirmation though.
Because this library is buggy:
```
Traceback (most recent call last):  5940kB time=00:00:00.75 bitrate=64880.6kbits/s speed=0.397x
  File "tracker.py", line 220, in <module>
    track_ids, frame_confidence, min_thresholds = trackers[id].update(packet['frame_idx'], im, detections, gt=gt)
  File "tracker.py", line 105, in update
    iou = r1.iou(r2)
AttributeError: 'Rectangle' object has no attribute 'iou'
```
r1 is the Rectangle object from here if I'm using this repo:
https://github.com/mitroadmaps/roadtracer-beta/blob/48ec58dcb92f48a952db324ab5105078d8fa5738/discoverlib/geom.py#L193
Apparently it doesn't have iou function implemented.

I'll implement iou function within it while waiting for confirmation

**Comment by favyen2** [comment]
You may need to set PYTHONPATH=`/path/to/otif/python` the library itself is here https://github.com/favyen/otif/tree/master/python/discoverlib
